# http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16.14.0
      - npm install
      
  build:
    commands:
      - echo Building Frontend Application
      - aws-deploy/scripts/codebuild.sh

artifacts:
  files:
    - '**/*'
  base-directory: .